matrix:
    include:
        - os: linux
          language: android
          sudo: false
          jdk: oraclejdk8
          dist: precise
        - os: osx
          language: generic
          jdk: oraclejdk8
          osx_image: xcode10
env:
  global:
  - TERM=dumb

android:
  components:
  - platform-tools
  - tools
  - build-tools-28.0.3
  - android-27
  - extra-android-support
  - extra-android-m2repository
  - extra-google-m2repository

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./gradlew :mpp:build ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./gradlew iosTest ; fi
