platform :ios, '10.0'
inhibit_all_warnings!
use_frameworks!

def pods
    pod 'Firebase/Core'
    pod 'Firebase/Auth'
    pod 'Firebase/Firestore'
    pod 'GoogleUtilities'
end

target 'iosApp' do
    pods
end
